- name: call apis
  hosts: localhost
  gather_facts: false

  vars:
    tower_host: towerclst01a.lab.shakey.org

  tasks:
    - name: launch tower job
      awx.awx.tower_job_launch:
        tower_host: "{{ tower_host }}"
        job_template: benchmark
      loop: "{{ range(0, 200) | list }}"
      register: job_launch
      retries: 5
      delay: 1
      until: job_launch is not failed
